### ISSUE TITLE
Image build failed at npm install -g @bigcommerce/stencil-cli

### ISSUE THREAD

**Issue by Butternbread** [aglensmith/docker-stencil-cli#1]
Tried to use this to easily install Stencil CLI on a fresh mac (Apple chip- Docker successfully installed), and ran into a bunch of errors when it hit `npm install -g @bigcommerce/stencil-cli`. Ultimately giving an Exit code 1. Any idea on an easy fix? Looks like node version issue.

**Comment by sergeifilippov** [comment]
I had the same issue.

```
git clone https://github.com/aligent/stencil-docker.git
cd ./stencil-docker
docker build -t docker-stencil ./
```

Here's the error message.

```
#10 111.1 gyp info spawn make
#10 111.1 gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
#10 111.1 make: Entering directory '/home/node/.npm-global/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-styles/node_modules/@bigcommerce/node-sass/build'
#10 111.1   g++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/home/node/.node-gyp/14.21.2/include/node -I/home/node/.node-gyp/14.21.2/src -I/home/node/.node-gyp/14.21.2/deps/openssl/config -I/home/node/.node-gyp/14.21.2/deps/openssl/openssl/include -I/home/node/.node-gyp/14.21.2/deps/uv/include -I/home/node/.node-gyp/14.21.2/deps/zlib -I/home/node/.node-gyp/14.21.2/deps/v8/include -I../../../../../../nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -MMD -MF ./Release/.deps/Release/obj.target/binding/src/binding.o.d.raw   -c -o Release/obj.target/binding/src/binding.o ../src/binding.cpp
#10 111.3 ../src/binding.cpp: In function 'void MakeCallback(uv_work_t*)':
#10 111.3 ../src/binding.cpp:246:39: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
#10 111.3      ctx_w->success_callback->Call(0, 0);
#10 111.3                                        ^
#10 111.3 In file included from ../src/binding.cpp:1:
#10 111.3 ../../../../../../nan/nan.h:1746:3: note: declared here
#10 111.3    Call(int argc, v8::Local<v8::Value> argv[]) const {
#10 111.3    ^~~~
#10 111.3 ../src/binding.cpp:254:40: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
#10 111.3      ctx_w->error_callback->Call(1, argv);
#10 111.3                                         ^
#10 111.3 In file included from ../src/binding.cpp:1:
#10 111.3 ../../../../../../nan/nan.h:1746:3: note: declared here
#10 111.3    Call(int argc, v8::Local<v8::Value> argv[]) const {
#10 111.3    ^~~~
#10 111.3 ../src/binding.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE render(Nan::NAN_METHOD_ARGS_TYPE)':
#10 111.3 ../src/binding.cpp:272:98: warning: cast between incompatible function types from 'void (*)(uv_work_t*)' {aka 'void (*)(uv_work_s*)'} to 'uv_after_work_cb' {aka 'void (*)(uv_work_s*, int)'} [-Wcast-function-type]
#10 111.3      int status = uv_queue_work(uv_default_loop(), &ctx_w->request, compile_it, (uv_after_work_cb)MakeCallback);
#10 111.3                                                                                                   ^~~~~~~~~~~~
#10 111.3 ../src/binding.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE render_file(Nan::NAN_METHOD_ARGS_TYPE)':
#10 111.3 ../src/binding.cpp:305:98: warning: cast between incompatible function types from 'void (*)(uv_work_t*)' {aka 'void (*)(uv_work_s*)'} to 'uv_after_work_cb' {aka 'void (*)(uv_work_s*, int)'} [-Wcast-function-type]
#10 111.3      int status = uv_queue_work(uv_default_loop(), &ctx_w->request, compile_it, (uv_after_work_cb)MakeCallback);
#10 111.3                                                                                                   ^~~~~~~~~~~~
#10 111.3 In file included from ../../../../../../nan/nan.h:60,
#10 111.3                  from ../src/binding.cpp:1:
#10 111.3 ../src/binding.cpp: At global scope:
#10 111.3 /home/node/.node-gyp/14.21.2/include/node/node.h:793:43: warning: cast between incompatible function types from 'void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)' {aka 'void (*)(v8::Local<v8::Object>)'} to 'node::addon_register_func' {aka 'void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)'} [-Wcast-function-type]
#10 111.3        (node::addon_register_func) (regfunc),                          \
#10 111.3                                            ^
#10 111.3 /home/node/.node-gyp/14.21.2/include/node/node.h:827:3: note: in expansion of macro 'NODE_MODULE_X'
#10 111.3    NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
#10 111.3    ^~~~~~~~~~~~~
#10 111.3 ../src/binding.cpp:343:1: note: in expansion of macro 'NODE_MODULE'
#10 111.3  NODE_MODULE(binding, RegisterModule);
#10 111.3  ^~~~~~~~~~~
#10 111.3 In file included from ../src/custom_function_bridge.h:7,
#10 111.3                  from ../src/sass_context_wrapper.h:9,
#10 111.3                  from ../src/binding.cpp:3:
#10 111.3 ../src/callback_bridge.h: In instantiation of 'static void CallbackBridge<T, L>::dispatched_async_uv_callback(uv_async_t*) [with T = Sass_Value*; L = void*; uv_async_t = uv_async_s]':
#10 111.3 ../src/callback_bridge.h:68:51:   required from 'CallbackBridge<T, L>::CallbackBridge(v8::Local<v8::Function>, bool) [with T = Sass_Value*; L = void*]'
#10 111.3 ../src/custom_function_bridge.h:11:109:   required from here
#10 111.3 ../src/callback_bridge.h:162:25: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
#10 111.3    bridge->callback->Call(argv_v8.size(), &argv_v8[0]);
#10 111.3    ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#10 111.3 In file included from ../src/binding.cpp:1:
#10 111.3 ../../../../../../nan/nan.h:1746:3: note: declared here
#10 111.3    Call(int argc, v8::Local<v8::Value> argv[]) const {
#10 111.3    ^~~~
#10 111.3 In file included from ../src/custom_function_bridge.h:7,
#10 111.3                  from ../src/sass_context_wrapper.h:9,
#10 111.3                  from ../src/binding.cpp:3:
#10 111.3 ../src/callback_bridge.h: In instantiation of 'static void CallbackBridge<T, L>::dispatched_async_uv_callback(uv_async_t*) [with T = Sass_Import**; L = void*; uv_async_t = uv_async_s]':
#10 111.3 ../src/callback_bridge.h:68:51:   required from 'CallbackBridge<T, L>::CallbackBridge(v8::Local<v8::Function>, bool) [with T = Sass_Import**; L = void*]'
#10 111.3 ../src/custom_importer_bridge.h:13:112:   required from here
#10 111.3 ../src/callback_bridge.h:162:25: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
#10 111.3    bridge->callback->Call(argv_v8.size(), &argv_v8[0]);
#10 111.3    ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#10 111.3 In file included from ../src/binding.cpp:1:
#10 111.3 ../../../../../../nan/nan.h:1746:3: note: declared here
#10 111.3    Call(int argc, v8::Local<v8::Value> argv[]) const {
#10 111.3    ^~~~
#10 111.6   g++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/home/node/.node-gyp/14.21.2/include/node -I/home/node/.node-gyp/14.21.2/src -I/home/node/.node-gyp/14.21.2/deps/openssl/config -I/home/node/.node-gyp/14.21.2/deps/openssl/openssl/include -I/home/node/.node-gyp/14.21.2/deps/uv/include -I/home/node/.node-gyp/14.21.2/deps/zlib -I/home/node/.node-gyp/14.21.2/deps/v8/include -I../../../../../../nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -MMD -MF ./Release/.deps/Release/obj.target/binding/src/create_string.o.d.raw   -c -o Release/obj.target/binding/src/create_string.o ../src/create_string.cpp
#10 111.9   g++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/home/node/.node-gyp/14.21.2/include/node -I/home/node/.node-gyp/14.21.2/src -I/home/node/.node-gyp/14.21.2/deps/openssl/config -I/home/node/.node-gyp/14.21.2/deps/openssl/openssl/include -I/home/node/.node-gyp/14.21.2/deps/uv/include -I/home/node/.node-gyp/14.21.2/deps/zlib -I/home/node/.node-gyp/14.21.2/deps/v8/include -I../../../../../../nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -MMD -MF ./Release/.deps/Release/obj.target/binding/src/custom_function_bridge.o.d.raw   -c -o Release/obj.target/binding/src/custom_function_bridge.o ../src/custom_function_bridge.cpp
#10 112.1 In file included from ../src/custom_function_bridge.h:7,
#10 112.1                  from ../src/custom_function_bridge.cpp:3:
#10 112.1 ../src/callback_bridge.h: In instantiation of 'static void CallbackBridge<T, L>::dispatched_async_uv_callback(uv_async_t*) [with T = Sass_Value*; L = void*; uv_async_t = uv_async_s]':
#10 112.1 ../src/callback_bridge.h:68:51:   required from 'CallbackBridge<T, L>::CallbackBridge(v8::Local<v8::Function>, bool) [with T = Sass_Value*; L = void*]'
#10 112.1 ../src/custom_function_bridge.h:11:109:   required from here
#10 112.1 ../src/callback_bridge.h:162:25: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
#10 112.1    bridge->callback->Call(argv_v8.size(), &argv_v8[0]);
#10 112.1    ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#10 112.1 In file included from ../src/custom_function_bridge.cpp:1:
#10 112.1 ../../../../../../nan/nan.h:1746:3: note: declared here
#10 112.1    Call(int argc, v8::Local<v8::Value> argv[]) const {
#10 112.1    ^~~~
#10 112.2   g++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/home/node/.node-gyp/14.21.2/include/node -I/home/node/.node-gyp/14.21.2/src -I/home/node/.node-gyp/14.21.2/deps/openssl/config -I/home/node/.node-gyp/14.21.2/deps/openssl/openssl/include -I/home/node/.node-gyp/14.21.2/deps/uv/include -I/home/node/.node-gyp/14.21.2/deps/zlib -I/home/node/.node-gyp/14.21.2/deps/v8/include -I../../../../../../nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -MMD -MF ./Release/.deps/Release/obj.target/binding/src/custom_importer_bridge.o.d.raw   -c -o Release/obj.target/binding/src/custom_importer_bridge.o ../src/custom_importer_bridge.cpp
#10 112.4 In file included from ../src/custom_importer_bridge.h:7,
#10 112.4                  from ../src/custom_importer_bridge.cpp:3:
#10 112.4 ../src/callback_bridge.h: In instantiation of 'static void CallbackBridge<T, L>::dispatched_async_uv_callback(uv_async_t*) [with T = Sass_Import**; L = void*; uv_async_t = uv_async_s]':
#10 112.4 ../src/callback_bridge.h:68:51:   required from 'CallbackBridge<T, L>::CallbackBridge(v8::Local<v8::Function>, bool) [with T = Sass_Import**; L = void*]'
#10 112.4 ../src/custom_importer_bridge.h:13:112:   required from here
#10 112.4 ../src/callback_bridge.h:162:25: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
#10 112.4    bridge->callback->Call(argv_v8.size(), &argv_v8[0]);
#10 112.4    ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#10 112.4 In file included from ../src/custom_importer_bridge.cpp:1:
#10 112.4 ../../../../../../nan/nan.h:1746:3: note: declared here
#10 112.4    Call(int argc, v8::Local<v8::Value> argv[]) const {
#10 112.4    ^~~~
#10 112.5   g++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/home/node/.node-gyp/14.21.2/include/node -I/home/node/.node-gyp/14.21.2/src -I/home/node/.node-gyp/14.21.2/deps/openssl/config -I/home/node/.node-gyp/14.21.2/deps/openssl/openssl/include -I/home/node/.node-gyp/14.21.2/deps/uv/include -I/home/node/.node-gyp/14.21.2/deps/zlib -I/home/node/.node-gyp/14.21.2/deps/v8/include -I../../../../../../nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -MMD -MF ./Release/.deps/Release/obj.target/binding/src/sass_context_wrapper.o.d.raw   -c -o Release/obj.target/binding/src/sass_context_wrapper.o ../src/sass_context_wrapper.cpp
#10 112.7 In file included from ../src/custom_function_bridge.h:7,
#10 112.7                  from ../src/sass_context_wrapper.h:9,
#10 112.7                  from ../src/sass_context_wrapper.cpp:1:
#10 112.7 ../src/callback_bridge.h: In instantiation of 'static void CallbackBridge<T, L>::dispatched_async_uv_callback(uv_async_t*) [with T = Sass_Value*; L = void*; uv_async_t = uv_async_s]':
#10 112.7 ../src/callback_bridge.h:68:51:   required from 'CallbackBridge<T, L>::CallbackBridge(v8::Local<v8::Function>, bool) [with T = Sass_Value*; L = void*]'
#10 112.7 ../src/custom_function_bridge.h:11:109:   required from here
#10 112.7 ../src/callback_bridge.h:162:25: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
#10 112.7    bridge->callback->Call(argv_v8.size(), &argv_v8[0]);
#10 112.7    ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#10 112.7 In file included from ../src/sass_context_wrapper.h:6,
#10 112.7                  from ../src/sass_context_wrapper.cpp:1:
#10 112.7 ../../../../../../nan/nan.h:1746:3: note: declared here
#10 112.7    Call(int argc, v8::Local<v8::Value> argv[]) const {
#10 112.7    ^~~~
#10 112.7 In file included from ../src/custom_function_bridge.h:7,
#10 112.7                  from ../src/sass_context_wrapper.h:9,
#10 112.7                  from ../src/sass_context_wrapper.cpp:1:
#10 112.7 ../src/callback_bridge.h: In instantiation of 'static void CallbackBridge<T, L>::dispatched_async_uv_callback(uv_async_t*) [with T = Sass_Import**; L = void*; uv_async_t = uv_async_s]':
#10 112.7 ../src/callback_bridge.h:68:51:   required from 'CallbackBridge<T, L>::CallbackBridge(v8::Local<v8::Function>, bool) [with T = Sass_Import**; L = void*]'
#10 112.7 ../src/custom_importer_bridge.h:13:112:   required from here
#10 112.7 ../src/callback_bridge.h:162:25: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
#10 112.7    bridge->callback->Call(argv_v8.size(), &argv_v8[0]);
#10 112.7    ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#10 112.7 In file included from ../src/sass_context_wrapper.h:6,
#10 112.7                  from ../src/sass_context_wrapper.cpp:1:
#10 112.7 ../../../../../../nan/nan.h:1746:3: note: declared here
#10 112.7    Call(int argc, v8::Local<v8::Value> argv[]) const {
#10 112.7    ^~~~
#10 112.7   g++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/home/node/.node-gyp/14.21.2/include/node -I/home/node/.node-gyp/14.21.2/src -I/home/node/.node-gyp/14.21.2/deps/openssl/config -I/home/node/.node-gyp/14.21.2/deps/openssl/openssl/include -I/home/node/.node-gyp/14.21.2/deps/uv/include -I/home/node/.node-gyp/14.21.2/deps/zlib -I/home/node/.node-gyp/14.21.2/deps/v8/include -I../../../../../../nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -MMD -MF ./Release/.deps/Release/obj.target/binding/src/sass_types/boolean.o.d.raw   -c -o Release/obj.target/binding/src/sass_types/boolean.o ../src/sass_types/boolean.cpp
#10 113.1   g++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/home/node/.node-gyp/14.21.2/include/node -I/home/node/.node-gyp/14.21.2/src -I/home/node/.node-gyp/14.21.2/deps/openssl/config -I/home/node/.node-gyp/14.21.2/deps/openssl/openssl/include -I/home/node/.node-gyp/14.21.2/deps/uv/include -I/home/node/.node-gyp/14.21.2/deps/zlib -I/home/node/.node-gyp/14.21.2/deps/v8/include -I../../../../../../nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -MMD -MF ./Release/.deps/Release/obj.target/binding/src/sass_types/color.o.d.raw   -c -o Release/obj.target/binding/src/sass_types/color.o ../src/sass_types/color.cpp
#10 113.3 ../src/sass_types/color.cpp: In static member function 'static Sass_Value* SassTypes::Color::construct(std::vector<v8::Local<v8::Value> >, Sass_Value**)':
#10 113.3 ../src/sass_types/color.cpp:30:26: warning: this statement may fall through [-Wimplicit-fallthrough=]
#10 113.3        a = Nan::To<double>(raw_val[3]).FromJust();
#10 113.3            ~~~~~~~~~~~~~~~^~~~~~~~~~~~
#10 113.3 ../src/sass_types/color.cpp:33:5: note: here
#10 113.3      case 3:
#10 113.3      ^~~~
#10 113.5   g++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/home/node/.node-gyp/14.21.2/include/node -I/home/node/.node-gyp/14.21.2/src -I/home/node/.node-gyp/14.21.2/deps/openssl/config -I/home/node/.node-gyp/14.21.2/deps/openssl/openssl/include -I/home/node/.node-gyp/14.21.2/deps/uv/include -I/home/node/.node-gyp/14.21.2/deps/zlib -I/home/node/.node-gyp/14.21.2/deps/v8/include -I../../../../../../nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -MMD -MF ./Release/.deps/Release/obj.target/binding/src/sass_types/error.o.d.raw   -c -o Release/obj.target/binding/src/sass_types/error.o ../src/sass_types/error.cpp
#10 113.8   g++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/home/node/.node-gyp/14.21.2/include/node -I/home/node/.node-gyp/14.21.2/src -I/home/node/.node-gyp/14.21.2/deps/openssl/config -I/home/node/.node-gyp/14.21.2/deps/openssl/openssl/include -I/home/node/.node-gyp/14.21.2/deps/uv/include -I/home/node/.node-gyp/14.21.2/deps/zlib -I/home/node/.node-gyp/14.21.2/deps/v8/include -I../../../../../../nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -MMD -MF ./Release/.deps/Release/obj.target/binding/src/sass_types/factory.o.d.raw   -c -o Release/obj.target/binding/src/sass_types/factory.o ../src/sass_types/factory.cpp
#10 114.2   g++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/home/node/.node-gyp/14.21.2/include/node -I/home/node/.node-gyp/14.21.2/src -I/home/node/.node-gyp/14.21.2/deps/openssl/config -I/home/node/.node-gyp/14.21.2/deps/openssl/openssl/include -I/home/node/.node-gyp/14.21.2/deps/uv/include -I/home/node/.node-gyp/14.21.2/deps/zlib -I/home/node/.node-gyp/14.21.2/deps/v8/include -I../../../../../../nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -MMD -MF ./Release/.deps/Release/obj.target/binding/src/sass_types/list.o.d.raw   -c -o Release/obj.target/binding/src/sass_types/list.o ../src/sass_types/list.cpp
#10 114.4 ../src/sass_types/list.cpp: In static member function 'static Sass_Value* SassTypes::List::construct(std::vector<v8::Local<v8::Value> >, Sass_Value**)':
#10 114.4 ../src/sass_types/list.cpp:28:73: error: too few arguments to function 'Sass_Value* sass_make_list(size_t, Sass_Separator, bool)'
#10 114.4      return *out = sass_make_list(length, comma ? SASS_COMMA : SASS_SPACE);
#10 114.4                                                                          ^
#10 114.4 In file included from ../src/sass_types/value.h:5,
#10 114.4                  from ../src/sass_types/sass_value_wrapper.h:7,
#10 114.4                  from ../src/sass_types/list.h:5,
#10 114.4                  from ../src/sass_types/list.cpp:2:
#10 114.4 /usr/include/sass/values.h:53:34: note: declared here
#10 114.4  ADDAPI union Sass_Value* ADDCALL sass_make_list    (size_t len, enum Sass_Separator sep, bool is_bracketed);
#10 114.4                                   ^~~~~~~~~~~~~~
#10 114.5 make: *** [binding.target.mk:124: Release/obj.target/binding/src/sass_types/list.o] Error 1
#10 114.5 make: Leaving directory '/home/node/.npm-global/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-styles/node_modules/@bigcommerce/node-sass/build'
#10 114.5 gyp ERR! build error 
#10 114.5 gyp ERR! stack Error: `make` failed with exit code: 2
#10 114.5 gyp ERR! stack     at ChildProcess.onExit (/home/node/.npm-global/lib/node_modules/@bigcommerce/stencil-cli/node_modules/node-gyp/lib/build.js:262:23)
#10 114.5 gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
#10 114.5 gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
#10 114.5 gyp ERR! System Linux 5.15.49-linuxkit
#10 114.5 gyp ERR! command "/usr/local/bin/node" "/home/node/.npm-global/lib/node_modules/@bigcommerce/stencil-cli/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
#10 114.5 gyp ERR! cwd /home/node/.npm-global/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-styles/node_modules/@bigcommerce/node-sass
#10 114.5 gyp ERR! node -v v14.21.2
#10 114.5 gyp ERR! node-gyp -v v3.8.0
#10 114.5 gyp ERR! not ok 
#10 114.5 Build failed
#10 115.5 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/@bigcommerce/stencil-cli/node_modules/chokidar/node_modules/fsevents):
#10 115.5 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
#10 115.5 
#10 115.5 npm ERR! code ELIFECYCLE
#10 115.5 npm ERR! errno 1
#10 115.5 npm ERR! @bigcommerce/node-sass@3.6.0 postinstall: `node scripts/build.js`
#10 115.5 npm ERR! Exit status 1
#10 115.5 npm ERR! 
#10 115.5 npm ERR! Failed at the @bigcommerce/node-sass@3.6.0 postinstall script.
#10 115.5 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#10 115.5 
#10 115.5 npm ERR! A complete log of this run can be found in:
#10 115.5 npm ERR!     /home/node/.npm/_logs/2023-01-18T02_43_59_816Z-debug.log
------
executor failed running [/bin/sh -c npm install -g @bigcommerce/stencil-cli@6.0.0 && stencil --version]: exit code: 1
```
